### ISSUE TITLE
JSON error on getDetails when it returns 5xx status code

### ISSUE THREAD

**Issue by PriOliveira** [ipinfo/python#107]
In the `getDetails` method, when the response status code is 5xx, it raises an error when attempting to read a JSON.

For example, when there is a 503 and it raises `ContentTypeError: Attempt to decode JSON with unexpected mimetype: text/plain`.

**Comment by PriOliveira** [comment]
@abdullahdevrel @max-ipinfo
Since the PR was merged, when do you think we could have a new version including the fix?

**Comment by max-ipinfo** [comment]
> @abdullahdevrel @max-ipinfo Since the PR was merged, when do you think we could have a new version including the fix?

We are planning to release a version as soon as possible. We will let you know in this thread when it is ready.

Thank you for your understanding.

**Comment by max-ipinfo** [comment]
@PriOliveira I now have maintainer access to our PyPi repository. I am hoping to push a new version with your change this week.

I will send you an update as soon as it's published. Thank you for your patience.

**Comment by max-ipinfo** [comment]
Published the latest version of the code as v5.1.0: 
https://pypi.org/project/ipinfo/5.1.0/
