### ISSUE TITLE
Error accessing api

### ISSUE THREAD

**Issue by ChaurandBenoit** [ipinfo/python#16]
Hello, I have an issue accessing to the API, this is my error, someone have a solution please ?

`requests.exceptions.ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /92.63.197.48 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 302 Found')))`

**Comment by UmanShahzad** [comment]
@ChaurandBenoit You're trying to use the client behind a proxy. You'll need to look at https://github.com/ipinfo/python#modifying-request-options and probably https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module or similar to figure out what custom request options to send to make it work in your setting.
