### ISSUE TITLE
Cache init parametes bug

### ISSUE THREAD

**Issue by juditnovak** [ipinfo/python#18]
https://github.com/ipinfo/python/blob/master/ipinfo/handler.py#L42

In case `cache_options` was defined, we end up "re-seinding" it, after having retrieved `maxsize` and `ttl` from the same dictionary. This way we multiply the same parameter in the function call, thus it can't perform.

**Comment by coderholic** [comment]
What do you mean "it can't perform"? They're set separately because they have defaults.

**Comment by UmanShahzad** [comment]
Thanks for the report @juditnovak. We'll fix that up and make a release.

**Comment by UmanShahzad** [comment]
@juditnovak Changed up the interface to `DefaultCache` a bit in this fix, so in case anyone was using it directly I've bumped the version to 3.0.0.

**Comment by juditnovak** [comment]
Thx much, this is what I call a prompt response and a quick fix! :-)
