### ISSUE TITLE
Details Bug

### ISSUE THREAD

**Issue by GitDoctor1996** [ipinfo/python#21]
I have a dataset of ip addresses. When I use the code to cycle through them at 506th ip address I get this error. AttributeError: loc is not a valid attribute of Details. This error does not make sense. Can you investigate?

```python
loc_list = []
for f in members['ip_address']:
    import ipinfo
    print(len(loc_list))
    access_token = '<REDACTED>'
    handler = ipinfo.getHandler(access_token, cache_options={'ttl':30, 'maxsize': 5000}, request_options={'timeout': 10})
    match = handler.getDetails(str(f))
    location = match.loc
    loc_list.append(location)
```

**Comment by bartbroere** [comment]
In Python an ``AttributeError`` simply means an attribute of an ``object`` does not exist. This can have any number of reasons. If you want to deal with missing values, you could either skip them, or add ``None`` as a placeholder.

Try replacing
``location = match.loc``
with 
``location = match.details.get('loc', None)``

The details attribute is a dictionary, containing the same values, which allows using a getter with a default value (in this case ``None``).

**Comment by UmanShahzad** [comment]
Hey @GitDoctor1996 , as @bartbroere said, you may sometimes not find a particular data point for certain IPs. Just as an example, the standard loopback address does not have a location:

```bash
$ curl ipinfo.io/127.0.0.1
{
  "ip": "127.0.0.1",
  "bogon": true
}
```

I suggest you use the solution @bartbroere recommended.
