### ISSUE TITLE
Please make a tutorial

### ISSUE THREAD

**Issue by jat28468** [ipinfo/python#22]
Please make a video how to use this feature

**Comment by UmanShahzad** [comment]
Hey @jat28468 , do you mean a video tutorial on how to use the SDK?

If so, that's not really in scope for this project - you can follow the very simple instructions found in the README.md file to get started. For example:

```python
>>> import ipinfo
>>> access_token = '123456789abc'
>>> handler = ipinfo.getHandler(access_token)
>>> ip_address = '216.239.36.21'
>>> details = handler.getDetails(ip_address)
>>> details.city
'Mountain View'
>>> details.loc
'37.3861,-122.0840'
```

If you'd like something more higher-level that doesn't use the API via code, you can try using it via the website at [https://ipinfo.io](https://ipinfo.io).
