### ISSUE TITLE
support for async

### ISSUE THREAD

**Issue by andrew-ld** [ipinfo/python#25]
we are in 2020, the network is used asynchronously now

**Comment by UmanShahzad** [comment]
Hey @andrew-ld , that's right, though the network has been used asynchronously for as long as it's been around! The Python ecosystem is catching up.

I'll look into adding an async version of the handler soon, while keeping the synchronous versions around for users without coroutines support in their version of Python, and for backwards compatibility.

**Comment by andrew-ld** [comment]
good!

**Comment by UmanShahzad** [comment]
@andrew-ld check out v4.0.0 - it has async support. Let me know if there are any issues with it.
