### ISSUE TITLE
ripe.net

### ISSUE THREAD

**Issue by sasanaskari** [ipinfo/python#34]
is there any way to use ripe records by your script?

**Comment by UmanShahzad** [comment]
@sasanaskari The scope of this project is just to present a simple-to-use API in Python abstracting the actual HTTP IPinfo API. It doesn't do any communication with ripe.net or any special processing of data at all.

**Comment by coderholic** [comment]
@sasanaskari if you've got some specific needs to RIPE data (or any IP whois data) feel free to reach out to our sales team: ipinfo.io/contact/sales
