### ISSUE TITLE
Unable to install ipinfo in demisto 

### ISSUE THREAD

**Issue by Aspirer0422** [ipinfo/python#39]
![PIPIssue](https://user-images.githubusercontent.com/59614224/106684728-088c5080-65ed-11eb-9400-3c31a10b775f.JPG)

**Comment by UmanShahzad** [comment]
@Aspirer0422 seems like it has nothing to do with ipinfo as it fails for your other installations as well.

Also, the issue seems to be something to do with your python version, likely not recognizing format strings.

**Comment by Aspirer0422** [comment]
Hi Uman,

Can you suggest resolutions on such python library issues which you might
have known from other customers global ?
