### ISSUE TITLE
get information is it proxy or vpn

### ISSUE THREAD

**Issue by sk3lk0** [ipinfo/python#51]
Good day, thanks for your service. Can you pls tell me, how i can get information about ip, like is it proxy or vpn?

**Comment by UmanShahzad** [comment]
https://ipinfo.io/proxy-vpn-detection-api is an intro to this kind of data, and you can register on https://ipinfo.io/signup and then go to https://ipinfo.io/account/addons to buy that specific data.

Then it'll be available in the responses to your requests. You'll be able to access it like this:

```python
handler = Handler("TOKEN")
details = handler.getDetails("8.8.8.8")

print(details.privacy["vpn"])
print(details.privacy["proxy"])
```
