### ISSUE TITLE
Ip_Getnet

### ISSUE THREAD

**Issue by tweetsakchutanee** [ipinfo/python#53]
curl ipinfo.io/124.122.223.235\?token=<token>
# Get details for 124.122.223.235

$ curl ipinfo.io/124.122.223.235?token=<token>

{
"ip": "124.122.223.235",
"hostname": "ppp-124-122-223-235.revip2.asianet.co.th",
"city": "Hat Yai",
"region": "Songkhla",
"country": "TH",
"loc": "7.0084,100.4767",
"org": "AS17552 True Online",
"postal": "90110",
"timezone": "Asia/Bangkok"
}

**Comment by UmanShahzad** [comment]
@tweetsakchutanee Please provide actual details about your issue.
