### ISSUE TITLE
Unexpected 403 response

### ISSUE THREAD

**Issue by nick-lironi-irvine** [ipinfo/python#58]
I have integrated this library into a Python 3.6 application which runs in ECS on AWS.
The library works as expected when running the application locally, and fails with a 403 response to the request when deployed into the AWS environment. I have done some debugging and this appears to not be a network issue; I can write equivalent code that calls the API using the requests library directly which returns the correct results, while making 'the same' request internally to the library fails with a 403 response.

Sample code to demonstrate this; it is a simplified version of the code running in my application 

```
import logging
import sys
import ipinfo
import requests

ip = "<some IP address>"
try:
   # headers copied from library internals
    headers = {
        "user-agent": "IPinfoClient/Python{version}/{sdk_version}".format(
            version=sys.version_info[0], sdk_version="4.2.1"
        ),
        "accept": "application/json",
        "authorization": "Bearer <my token>",
    }

    response = requests.get(url="https://ipinfo.io/" + ip, headers=headers)
    logging.warning("Headers: %s", response.headers)
    logging.warning("Text: %s", response.text)
    response.raise_for_status() # this does not fail, the expected values are logged above
except Exception as e:
    logging.warning("manual call failed", exc_info=e)

try:
    return ipinfo.getHandler(<my token>).getDetails(ip_address=ip) # this fails
except Exception as e:
    logging.warning(
        "Failed to get IP Location Details", exc_info=e,
    )
    return None
```

The output of the call to the library is 
```
File "/home/stellar/virtualenv/lib/python3.6/site-packages/ipinfo/handler.py", line 98, in getDetails
    response.raise_for_status()
File "/home/stellar/virtualenv/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ipinfo.io/<IP address>
```

I would appreciate any assistance in diagnosing or fixing this issue

**Comment by UmanShahzad** [comment]
We could throw a special error type `APIError()` which takes the JSON body as a parameter. Will add this at some point, sure!

**Comment by UmanShahzad** [comment]
@SobanMahmood can you check this one out when free.
