### ISSUE TITLE
4.3.0 release is giving an error

### ISSUE THREAD

**Issue by wlongabaugh** [ipinfo/python#63]
Hello:

Code that has been working without a hitch for months now throws this error when I call: `handler = ipinfo.getHandler(access_token)` after a call to `pip install ipinfo` on a fresh VM:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/ipinfo/eu.json'

I confirm that `version.py` contains `SDK_VERSION = "4.3.0"`

**Comment by UmanShahzad** [comment]
Looks like it wasn't included in our `MANIFEST.in`. Apologies for this - please try to install again, a patch fix at 4.3.1 has it included.

**Comment by wlongabaugh** [comment]
Works now. Thanks!
