### ISSUE TITLE
Bogon check generates error if ip_address is None

### ISSUE THREAD

**Issue by alimanfoo** [ipinfo/python#74]
https://github.com/ipinfo/python/blob/a003e431ff960d50d9f52c02b4bb418ee939039e/ipinfo/handler.py#L114

The `ip_address` parameter is optional, but ValueError will be raised due to the bogon check here if `ip_address` is None.

**Comment by UmanShahzad** [comment]
Good find, thanks. @rm-Umar let's take care of that case and do a patch release ASAP!

**Comment by rm-Umar** [comment]
@alimanfoo thank you for reporting the issue is fixed in the new patch you can upgrade your package and it'll resolve your issue `pip install ipinfo --upgrade`
