### ISSUE TITLE
Error when running program

### ISSUE THREAD

**Issue by th3knv** [ipinfo/python#78]
hello, as i saw in docs i can use these options to print out results . But it shows error when i run program .I have _free plan_ 

```py
import ipinfo

access_token = 'MY-API'
ip_address = '130.117.190.132'
handler = ipinfo.getHandler(access_token)
details = handler.getDetails(ip_address)
print(details.ip)
print(details.hostname)
print(details.city)
print(details.region)
print(details.country)
print(details.loc)
print(details.org)
print(details.postal)
print(details.timezone)
```

**The error that it prints is :**
  ```py
  File "c:Users\User\Files\VsCode\pyprojects\test.py", line 8, in <module>
    print(details.hostname)
  File "C:\Python\Python391\lib\site-packages\ipinfo\details.py", line 18, in __getattr__
    raise AttributeError(
AttributeError: hostname is not a valid attribute of Details**
```
**Note that as i tested, when i enter different ip, it may print other error except 'hostname' option**

**Comment by UmanShahzad** [comment]
@th3knv `130.117.190.132` doesn't have a hostname so that's why it fails. What other field did you try that could cause this and for what IP?

But in general if this happens it's because of a piece of data missing for that input IP.

**Comment by UmanShahzad** [comment]
We can't put 'Not found', though we could put an empty string. This mostly reflects the API results - the API also doesn't return a `hostname` field if it's missing. I think you can just check `if hostname in data` or something similar as a safety check.

**Comment by th3knv** [comment]
> 

Thanks for the help, problem solved. With Chat Gpt's help : 

```py
def get_detail(ip_address, detail):
                handler = ipinfo.getHandler(access_token)

                try:
                    details = handler.getDetails(ip_address)
                    if hasattr(details, detail):
                        return getattr(details, detail)
                    else:
                        return 'Not Found'
                except ipinfo.exceptions.AddressNotFoundError:
                    return 'Not Found'
```
with this way it sends back 'Not found' result instead of printing error 👍
