### ISSUE TITLE
details.all is not json serializable because of the ip_address object

### ISSUE THREAD

**Issue by coderholic** [ipinfo/python#8]

**Comment by bartbroere** [comment]
For anyone googling this: The key ``ip_address`` contains an instance of ``IPv4Address``, and the key ``ip`` contains the IP address encoded as a string. To be able to serialize this in json, you could simply drop the key ``ip_address`` with the ``del`` keyword.
 
```python
import json
import ipinfo

handler = ipinfo.getHandler("deadbeef")

ip_details = handler.getDetails("8.8.8.8")
del ip_details["ip_address"]
ip_details_serialized = json.dumps(ip_details)
```

**Comment by UmanShahzad** [comment]
I think there's we could probably just avoid inserting the `IPv4Address` type object in there so that it's just the string you get from the `ip` field via the API's JSON response. Though we'd have to bump the major version because people may be relying on it being `IPv4Address` type.

**Comment by UmanShahzad** [comment]
Released https://pypi.org/project/ipinfo/2.0.0/ without the ip_address key, and with a changelog entry in https://github.com/ipinfo/python/blob/master/CHANGELOG.md.
