### ISSUE TITLE
Release v4.4.2 release doesn't contain the latest code

### ISSUE THREAD

**Issue by robingoth** [ipinfo/python#80]
The release was made in November, but the last commit was made in March.
The latest code contains this feature to add custom headers, which is also documented, but when you `pip install` the library, this feature is not there.

I ran into an issue when I limited my token to a specific referrer, but then the library was not sending the corresponding header, which resulted in a very ambiguous HTTP 400 error:
```
return self.handler.getDetails(ip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/ipinfo/handler.py", line 140, in getDetails
    response.raise_for_status()
  File ".../lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://ipinfo.io/89.58.48.55
```

Could you please make a new release with the latest code?

**Comment by UmanShahzad** [comment]
@robingoth The latest code isn't yet released indeed - that's the only change we made since 4.4.2, and didn't get to releasing it. We can release it as a 4.4.3 soon. Thanks for this!

@awaismslm can you please handle that?
