### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by adm1nSQL** [ipinfo/python#96]
```
import requests


headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (HTML, like Gecko) '
                  'Chrome/108.0.0.0 '
                  'Safari/537.36'
}
url = "https://ipinfo.io/8.8.8.8?token=***********"
response = requests.get(url, headers=headers)
data = response.json()

print(data)
```

For a long time in the past, I used the above code to correctly return JSON content. Since two days ago, error 406 has been returned as follows
```
{'error': '406', 'request': '/8.8.8.8?token=***********"', 'data': "If you believe you've received this in error, please open a support request."}
```

**Comment by UmanShahzad** [comment]
@adm1nSQL Can you share your source IP? It may be hitting some firewall or something.

**Comment by adm1nSQL** [comment]
> @adm1nSQL Can you share your source IP? It may be hitting some firewall or something.

199.15.77.60 , please check it, thanks

**Comment by adm1nSQL** [comment]
> @adm1nSQL Can you tell me a little bit more about your ISP and setup in general?
if I use proxy, will be success?

**Comment by adm1nSQL** [comment]
> I would like to understand more about where your request is originating from and what ISP you have.

I have tried some proxies and they are working properly， only 199.15.77.60 is bad
